motosucata/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^redactor/', include('redactor.urls')),
    #(r'^pages/', include('django.contrib.flatpages.urls')),
    
    url(r'^$', 'products.views.index', name='home'),
    url(r'^contact/?$', 'products.views.contact'),
    url(r'^(?P<slug>[\w_-]+)$', 'products.views.details'),
    url(r'^q/(?P<column>(type)?)/?(?P<text>[\w -]{0,100})$', 'products.views.search'),
)

try:
    urlpatterns += patterns('', (r'^flexselect/', include('flexselect.urls')), )
except ImportError:
    urlpatterns += patterns('flexselect.views', (r'field_changed', 'field_changed'), )

if settings.LOCAL:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
# -*- coding: utf-8 -*-
import random, glob, os, shutil
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from embed_video.fields import EmbedVideoField
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.template.defaultfilters import slugify
from django.conf import settings

from redactor.fields import RedactorField
from easy_thumbnails.fields import ThumbnailerImageField



type_choices = (
    (1, u'Sucata Inteira'),
    (2, u'Moto Documentada'),
    (3, u'Peça avulsa'),
)

state_choices = (
    ('SP', u'São Paulo'),
    ('RJ', u'Rio de Janeiro'),
)



class Brake(models.Model):
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        verbose_name = u"sistema de freio"
        verbose_name_plural = u"sistemas de freio"
        
    name = models.CharField(u'Nome', max_length=80)



class Mark(models.Model):
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        verbose_name = u"marca"
    
    name = models.CharField(u'Nome', max_length=80)



class Model(models.Model):
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        verbose_name = u"modelo"
    
    mark = models.ForeignKey(Mark, verbose_name=u"Marca")
    name = models.CharField(u'Nome', max_length=80)



class Photo(models.Model):
    class Meta:
        verbose_name = u"foto"
    
    def save(self):
        if self.image:
            if self.id:
                obj_photo = Photo.objects.get(id=self.id)
                if self.image not in [obj_photo.image]:
                    for fl in glob.glob("%s/%s*" % (settings.MEDIA_ROOT,obj_photo.image)):
                        os.remove(fl)
            
            super(Photo, self).save()
    
    def delete(self):
        obj_photo = Photo.objects.get(id=self.id)
        super(Photo, self).delete()
        for fl in glob.glob("%s/%s*" % (settings.MEDIA_ROOT,obj_photo.image)):
            os.remove(fl)
    
    def get_upload_to_image(self, filename):
        ext = filename[-3:].lower()
        if ext == 'peg': ext='jpeg'        
        return 'products/%s/%s_%s.%s' % (self.products.slug, datetime.now().strftime('%Y%m%d%H%M%S'), str(random.randint(00000,99999)), ext)
    
    def __unicode__(self):
        return u'%s' % self.image
    
    products = models.ForeignKey('Product')
    image = ThumbnailerImageField(u'Imagem', blank=True, upload_to = get_upload_to_image, resize_source=dict(size=(800, 600), sharpen=True, crop="scale"))
    title = models.CharField(u'Título', max_length=100, blank=True)
    main = models.BooleanField(u'Foto de capa')



class StartingSystem(models.Model):
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        verbose_name = u"sistema de partida"
        verbose_name_plural = u"sistemas de partida"
        
    name = models.CharField(max_length=40)



class ProductActivatedManager(models.Manager):
    def get_queryset(self):
        return super(ProductActivatedManager, self).get_queryset().filter(published=True).order_by('-banner_home','-updated_at')

class Product(models.Model):
    def __unicode__(self):
        return u'%s' % self.title
    
    class Meta:
        verbose_name = u"produto"
    
    def save(self, *args, **kwargs):
        if not self.id:
            super(Product, self).save(*args, **kwargs)
            self.slug = slugify(str(self.id) + ' ' + self.title)
        super(Product, self).save(*args, **kwargs)
        
    def delete(self):
        slug = self.slug
        super(Product, self).delete()
        
        dir = '%s/products/%s' % (settings.MEDIA_ROOT, slug)
        
        if os.path.exists(dir):
            shutil.rmtree(dir)
    
    def clean(self):
        if not self.model.mark.id == self.mark.id:
            raise ValidationError(u'O Modelo selecionado não condiz com a Marca')
    
    def get_absolute_url(self):
        return reverse('products.views.details', kwargs={'slug': self.slug})
    
    def main_photo_set(self):
        photo = self.photo_set.order_by('-main','id')
        return photo[0] if photo else None
    
    brakes = models.ForeignKey(Brake, verbose_name=u"Sistema de Freio")
    starting_system = models.ForeignKey('StartingSystem', verbose_name=u"Sistema de Partida")
    mark = models.ForeignKey(Mark, verbose_name=u"Marca")
    model = models.ForeignKey(Model, verbose_name=u"Modelo")
    owner = models.ForeignKey(User, verbose_name=u"Usuário")
    
    type = models.IntegerField(u'Tipo', choices=type_choices)
    title = models.CharField(u'Título', max_length=160)
    slug = models.SlugField(max_length=200)
    video_link = EmbedVideoField(u'Vídeo', max_length=160, blank=True, help_text=u"Informe o link do youtube, vimeo ou soundcloud")
    #video_link = models.URLField(u'Vídeo', max_length=160, blank=True, help_text=u"Informe o link do youtube")
    km = models.IntegerField()
    cc = models.IntegerField(u'Cilindradas', null=True, blank=True)
    version = models.CharField(u'Versão', max_length=40, blank=True)
    year = models.IntegerField(u'Ano', blank=True, null=True)
    price = models.DecimalField(u'Preço', max_digits=6, decimal_places=2, blank=True, null=True)
    description = RedactorField(verbose_name=u'Descrição', allow_file_upload=False, allow_image_upload=False, blank=True)
    #description = models.TextField(u'Descrição', blank=True)
    state = models.CharField(u'Estado', max_length=4, blank=True,choices=state_choices)
    city = models.CharField(u'Cidade', max_length=120, blank=True)
    phone = models.CharField(u'Telefone', max_length=120, blank=True)
    used = models.BooleanField(u'Usado') # This field type is a guess.
    published = models.BooleanField(u'Publicado', default=True) # This field type is a guess.
    banner_home = models.BooleanField(u'Banner principal', default=False, help_text=u"Marque esta opção para que o produto apareça em posição de destaque no site")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    u''' Managers '''
    objects     = models.Manager()
    activated   = ProductActivatedManager()

products/forms.py
# -*- coding: utf-8 -*-

from django import forms

class ContactForm(forms.Form):
    name    = forms.CharField(label=u'Nome', max_length=50, required=True)
    email   = forms.EmailField(label=u'e-mail', max_length=80, required=False)
    phone   = forms.CharField(label=u'Telefone(s)', max_length=50, required=False)
    message = forms.CharField(label=u'Mensagem', widget=forms.Textarea)
    
    def clean(self):
        cleaned_data = super(ContactForm, self).clean()
        email = cleaned_data.get("email")
        phone = cleaned_data.get("phone")

        if (str(email).strip() == "" and str(phone).strip()==""):
            self._errors["email"] = self.error_class([u"Informe um e-mail ou telefone para contato"])
            
            del cleaned_data["email"]
        
        return cleaned_data

products/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponse
from django.template import RequestContext, loader
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import mail_managers
from django.conf import settings

from models import Product, type_choices
from forms import ContactForm
from utils import get_query


def index(request):
    product_list    = Product.activated.all()[:9]
    product_banner  = product_list[:1]
    product_list    = product_list[1:8]
    
    template = loader.get_template('products/index.html')
    context = RequestContext(request, {
        'product_banner': product_banner,
        'product_list'  : product_list,
    })
    return HttpResponse(template.render(context))


def search(request, column="", text=""):
    query_string = ''
    product_list = None
    if text.strip():
        if column == 'type':
            type_reverse = dict((v.lower().replace(' ','-'), k) for k, v in type_choices)
            try:
                product_list = Product.activated.filter(type=type_reverse[text])
            except KeyError:
                product_list = None
                
        else:
            query_string = text.replace('-',' ')
            entry_query = get_query(query_string, ['title', 'mark__name', 'model__name', 'description',])
            product_list = Product.activated.filter(entry_query)
    
    template = loader.get_template('products/search_results.html')
    context = RequestContext(request, {
        'query_string': query_string, 
        'product_list': product_list,
    })
    return HttpResponse(template.render(context))


def details(request, slug):
    try:
        product = Product.activated.get(slug=slug)
    except ObjectDoesNotExist:
        product = None
    
    try:
        http_referer = request.environ['HTTP_REFERER']
    except KeyError:
        http_referer = '/'
    
    mail_sent = None
    
    if request.method == 'POST':
        http_referer = request.POST['http_referer']
        
        form = ContactForm(request.POST)
        
        if form.is_valid():
            subject = u'Interesse em ' + product.title
            url     = request.build_absolute_uri()
            name    = form.cleaned_data['name']
            email   = form.cleaned_data['email']
            phone   = form.cleaned_data['phone']
            message = form.cleaned_data['message']
            message = u'Mensagem enviada por %s <%s> %s \n\n%s \n\n\nMensagem enviada através da página:\n%s' % (name, email, phone, message, url)
            
            try:
                mail_managers(subject, message, fail_silently = False)
                mail_sent = True
            except Exception as e:
                mail_sent = False
                if settings.DEBUG:
                    raise # reraises the exception
    else:
        form = ContactForm()
    
    template = loader.get_template('products/details.html')
    context = RequestContext(request, {
        'product'   : product,
        'form'      : form,
        'mail_sent' : mail_sent,
        'http_referer' : http_referer,
    })
    return HttpResponse(template.render(context))


def contact(request):
    
    mail_sent = None
    
    if request.method == 'POST':
        
        form = ContactForm(request.POST)
        if form.is_valid():
            url     = request.build_absolute_uri()
            name    = form.cleaned_data['name']
            email   = form.cleaned_data['email']
            phone   = form.cleaned_data['phone']
            subject = u'Contato de ' + name
            message = form.cleaned_data['message']
            message = u'Mensagem enviada por %s <%s> %s \n\n%s \n\n\nMensagem enviada através da página:\n%s' % (name, email, phone, message, url)
            
            try:
                mail_managers(subject, message, fail_silently = False)
                mail_sent = True
            except Exception as e:
                mail_sent = False
                if settings.DEBUG:
                    raise # reraises the exception
    else:
        form = ContactForm()
    
    template = loader.get_template('products/contact.html')
    context = RequestContext(request, {
        'form'      : form,
        'mail_sent' : mail_sent,
    })
    return HttpResponse(template.render(context))

templates/products/_search_form.html
<div id="search-wrap">
    <form action="" id="search-form" name="search-form">
        <input type="text" name="text" id="text" value="{{query_string}}" placeholder="Digite o que você procura" />
        <input type="submit" value="Buscar" />
    </form>
</div>

templates/products/contact.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block title %} Envie uma mensagem {% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'products/css/products.css' %}">
{% endblock %}

{% block script %}
<script src="{% static 'products/js/contact_form.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block content %}

<div class="section">
    <div class="w-container">
        
        <div class="w-row">            
            <div class="w-col w-col-12" id="contact-form">
                <fieldset>
                    <legend>
                        &nbsp; Contato &nbsp;
                    </legend>

                    <form name="form-contact" id="form-contact" action="" method="post" accept-charset="utf-8">
                        {% if mail_sent == True %}
                        <p class='mail-message mail-success'>Mensagem enviada com sucesso!<br/>Em breve entraremos em contato.</p>
                        {% elif mail_sent == False %}
                        <p class='mail-message mail-error'>Não foi possível enviar a mensagem!<br/>Por favor, tente novamente.</p>
                        {% endif %}
                        
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>
                            <input type="submit" value="Enviar"/>
                        </p>
                    </form>
                </fieldset>
            </div>
        </div>
        
    </div>
</div>

{% endblock %}

templates/products/details.html
{% extends 'layout.html' %}
{% load thumbnail %}
{% load embed_video_tags %}
{% load staticfiles %}

{% block title %} {{ product.title }} {% endblock %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'products/css/products.css' %}">
{% endblock %}

{% block script %}
<script src="{% static 'products/js/products.js' %}" type="text/javascript" charset="utf-8"></script>
<script src="{% static 'products/js/contact_form.js' %}" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript" src="{% static 'products/js/sharethis_buttons.js' %}"></script>
<script type="text/javascript">stLight.options({publisher: "ur-bd7ed52e-b68b-3aae-ea66-8940604ece00", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
{% endblock %}


{% block content %}

{% if not product %}
<div class="section hero">
    <div class="w-container">
        <p>Desculpe, este produto está indisponível ou não existe em nosso banco de dados.</p>
    </div>
</div>
<div class="section">
    <div class="w-container">
        {% include "products/_search_form.html" %}
    </div>
</div>

{% else %}

<div class="w-container" id="nav-products">
    <div> <a href="{{http_referer}}" title="voltar">&laquo; voltar</a> </div>
</div>
<div class="section hero hero-cuztomized">
    <div class="w-container">
        <div class="w-row">
            {% if product.photo_set.count %}
            <div class="w-col w-col-6 w-col-right"> <h2>{{ product.title }}</h2> </div>
            <div class="w-col w-col-6 center">
                {% for photo in product.photo_set.all %}
                <div class="tn_photo" id="tn_photo_{{photo.id}}">
                    <img width="auto" height="auto" src="{{ photo.image|thumbnail_url:'small'|default:'holder.js/40x40' }}" title="{{photo.title}}" alt="{{photo.title}}">
                    <input type="hidden" id="url_img_{{photo.id}}" value="{{ photo.image|thumbnail_url:'large'|default:'holder.js/500x375' }}"/>
                </div>
                {% endfor %}
            </div>
            
            {% else %}
            <div class="w-col w-col-6"> <h2>{{ product.title }}</h2> </div>
            {% endif %}
        </div>
        
        
        
        <div class="w-row">
            {% if product.photo_set.count %}
            <div class="w-col w-col-6 center">
                <img id="large-image" width="auto" height="auto" />
                <p id="image-description"> </p>
            </div>
            {% elif product.video_link %}
            <div class="w-col w-col-6">
                <div class="video_link">{% video product.video_link '100% x 100%' %}</div>
            </div>
            {% endif %}
            
            
            
            <div class="w-col w-col-3">
                <p class="price">R$ {{ product.price }}</p>
                
                <p>
                    {{ product.get_type_display }} | {{ product.year|stringformat:"s" }} 
                    {% if product.used %} - Usada{% endif %}
                </p>
                
                <p>
                    {{ product.mark }} {{ product.model }} - {{ product.version }} | {{ product.km }} Km 
                    {% if product.cc %} | {{product.cc}} cc {% endif %}
                </p>
                
                <p>
                    Freios: {{ product.brakes }} | Partida: {{ product.starting_system }}
                </p>
                
                <p>{{ product.city }} - {{ product.state }}</p>
                
                <p><strong>{{ product.phone }}</strong></p>
                
                <div id="social-buttons">
                    <span class='st_facebook' title="Facebook"> </span>
                    <span class='st_twitter' title="Tweet"> </span>
                    <span class='st_googleplus' title="Google +"> </span>
                </div>
            </div>
            
            <div class="w-col w-col-3 contact-product" id="contact-form">
                <fieldset>
                    <legend>
                        &nbsp; Dúvida ou Proposta &nbsp;
                    </legend>

                    <form name="form-contact" id="form-contact" action="" method="post" accept-charset="utf-8">
                        {% if mail_sent == True %}
                        <p class='mail-message mail-success'>Mensagem enviada com sucesso!<br/>Em breve entraremos em contato.</p>
                        {% elif mail_sent == False %}
                        <p class='mail-message mail-error'>Não foi possível enviar a mensagem!<br/>Por favor, tente novamente.</p>
                        {% endif %}
                        
                        {% csrf_token %}
                        <input type="hidden" name="http_referer" value="{{http_referer}}" id="http_referer"/>
                        {{ form.as_p }}
                        <p>
                            <input type="submit" value="Enviar"/>
                        </p>
                    </form>
                </fieldset>
            </div>
        </div>
    </div>
</div>
<div class="section">
    <div class="w-container">
        
        <div class="w-row">
            <div class="w-col w-col-12">
                {% autoescape off %}
                <div class="description">{{ product.description }}</div>
                {% endautoescape %}
            </div>
        </div>
        
        
        {% if product.photo_set.count %}
        <div class="w-row">
            <div class="w-col w-col-6">
                <div class="video_link">{% video product.video_link '100% x 100%' %}</div>
            </div>
        </div>
        {% endif %}
        
    </div>
</div>
{% endif %}

{% endblock %}

templates/products/index.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %} Início {% endblock %}

{% block content %}

<div class="section hero">
    <div class="w-container">
        {% for product in product_banner %}
        <div class="w-row">
            <div class="w-col w-col-6 center">
                <img class="hero-image" width="auto" height="auto" src="{{ product.main_photo_set.image|thumbnail_url:'medium'|default:'holder.js/270x270' }}">
            </div>
            <div class="w-col w-col-6 hero-column">
                <h1>{{ product.title }}</h1>
                <p>{{ product.mark }} {{ product.model }} - {{ product.get_type_display }} | {{ product.year|stringformat:"s" }} | {{ product.km }} Km</p>
                <p>{{ product.description|striptags|truncatewords:23 }}</p>
                <a class="button action" href="{{ product.get_absolute_url }}" title="Confira!">R$ {{ product.price }}</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="section">
    <div class="w-container">
        
        {% include "products/_search_form.html" %}
        
        <div class="w-row">
            {% for product in product_list %}
            <div class="w-col w-col-3 w-col-small-6">
                <img src='{{ product.main_photo_set.image|thumbnail_url:"small"|default:"holder.js/140x140" }}'>
                <h3>{{ product.title }}</h3>
                <p>{{ product.get_type_display }}</p>
                <p>{{ product.year|stringformat:"s" }} | {{ product.km }} Km</p>
                <a class="button" href="{{ product.get_absolute_url }}" title="Confira!">R$ {{ product.price }}</a>
            </div>
            
            {% if forloop.counter|divisibleby:"4" %}
            </div><div class="w-row">
            {% endif %}
            
            {% empty %}
            
            <p>Em breve publicaremos os produtos disponíveis, aguardem!</p>
            
            {% endfor %}
        </div>
        
        
        <div class="w-row special-row">
            <div class="w-col w-col-8 special-column">
                <h3>Special text right here</h3>
                <p>This is a feature description. Donec ullamcorper nulla non metus auctor fringilla. Sed posuere consectetur est at lobortis. This is a feature description. Donec ullamcorper nulla non metus auctor fringilla. Sed posuere consectetur est at lobortis.</p>
            </div>
            <div class="w-col w-col-4 email-column"><a class="button action" href="#">Email Us</a>
            </div>
        </div>
        
    </div>
</div>

{% endblock %}

templates/products/search_results.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %} Resultado da busca {% endblock %}

{% block content %}

<div class="section hero"> </div>
<div class="section">
    <div class="w-container">
        
        {% include "products/_search_form.html" %}
        
        <div class="w-row">
            {% for product in product_list %}
            <div class="w-col w-col-3 w-col-small-6">
                <img src='{{ product.main_photo_set.image|thumbnail_url:"small"|default:"holder.js/140x140" }}'>
                <h3>{{ product.title }}</h3>
                <p>{{ product.get_type_display }}</p>
                <p>{{ product.year|stringformat:"s" }} | {{ product.km }} Km</p>
                <a class="button" href="{{ product.get_absolute_url }}" title="Confira!">R$ {{ product.price }}</a>
            </div>
            
            {% if forloop.counter|divisibleby:"4" %}
            </div><div class="w-row">
            {% endif %}
            
            {% empty %}
            
            <p>Nenhum produto encontrado! Por favor, tente novamente.</p>
            
            {% endfor %}
        </div>
        
    </div>
</div>

{% endblock %}